# Generated by Django 5.2 on 2025-04-25 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='bid_count',
        ),
    ]
